// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeilwtqrlbmfibzhxvox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlaWx3dHFybGJtZmliemh4dm94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODI4NzAsImV4cCI6MjA2ODY1ODg3MH0.DoVjX7fHcrJuFNHRAzQryJ3dmeUddANoORmJkBGzNE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});